namespace RageLib.Resources.GTA5.PC.Meta.Enums
{
    public enum Unk_1931949281 : int
    {
        LIGHTSHAFT_DENSITYTYPE_CONSTANT = 0,
        LIGHTSHAFT_DENSITYTYPE_SOFT = 1,
        LIGHTSHAFT_DENSITYTYPE_SOFT_SHADOW = 2,
        LIGHTSHAFT_DENSITYTYPE_SOFT_SHADOW_HD = 3,
        LIGHTSHAFT_DENSITYTYPE_LINEAR = 4,
        LIGHTSHAFT_DENSITYTYPE_LINEAR_GRADIENT = 5,
        LIGHTSHAFT_DENSITYTYPE_QUADRATIC = 6,
        LIGHTSHAFT_DENSITYTYPE_QUADRATIC_GRADIENT = 7,
    }
}
